stages:
  - test

test:
  stage: test
  image: python:3.6
  variables:
    PIP_CACHE_DIR: "pip-cache"
    POSTGRES_DB: document_merge_service
    POSTGRES_USER: document_merge_service
    POSTGRES_PASSWORD: document_merge_service
    DATABASE_HOST: postgres
  script:
    - echo "ENV=ci" > .env
    - make install-dev
    - make test
  services:
    - postgres
  cache:
    key: "$CI_PROJECT_NAME"
    paths:
      - pip-cache


# Pyup example: Configure USER_TOKEN as secret environment variables
# and potentially adjust gitlab.com with your custom instance
# pyup:
#   stage: test
#   image: python:3.6
#   variables:
#     PIP_CACHE_DIR: "pip-cache"
#   cache:
#     key: "$CI_PROJECT_NAME"
#     paths:
#       - pip-cache
#   script:
#     - pip install -U pyupio
#     - pyup --provider gitlab --repo=$CI_PROJECT_ID --user-token=$USER_TOKEN@https://gitlab.com
#   only:
#     - master
